// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package MI_PERIFERICO_pkg;

    localparam MI_PERIFERICO_DATA_WIDTH = 32;
    localparam MI_PERIFERICO_MIN_ADDR_WIDTH = 8;
    localparam MI_PERIFERICO_SIZE = 'hf8;

    typedef struct {
        logic [2:0] value;
    } MI_PERIFERICO__CTRL__SIZE__out_t;

    typedef struct {
        logic [4:0] value;
    } MI_PERIFERICO__CTRL__RESERVED1__out_t;

    typedef struct {
        logic [1:0] value;
    } MI_PERIFERICO__CTRL__OFFSET__out_t;

    typedef struct {
        logic [5:0] value;
    } MI_PERIFERICO__CTRL__RESERVED2__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__CTRL__CLR__out_t;

    typedef struct {
        logic [14:0] value;
    } MI_PERIFERICO__CTRL__RESERVED3__out_t;

    typedef struct {
        MI_PERIFERICO__CTRL__SIZE__out_t SIZE;
        MI_PERIFERICO__CTRL__RESERVED1__out_t RESERVED1;
        MI_PERIFERICO__CTRL__OFFSET__out_t OFFSET;
        MI_PERIFERICO__CTRL__RESERVED2__out_t RESERVED2;
        MI_PERIFERICO__CTRL__CLR__out_t CLR;
        MI_PERIFERICO__CTRL__RESERVED3__out_t RESERVED3;
    } MI_PERIFERICO__CTRL__out_t;

    typedef struct {
        logic [7:0] value;
    } MI_PERIFERICO__STATUS__CNT_DROP__out_t;

    typedef struct {
        logic [3:0] value;
    } MI_PERIFERICO__STATUS__RX_LVL__out_t;

    typedef struct {
        logic [3:0] value;
    } MI_PERIFERICO__STATUS__RESERVED1__out_t;

    typedef struct {
        logic [3:0] value;
    } MI_PERIFERICO__STATUS__TX_LVL__out_t;

    typedef struct {
        logic [11:0] value;
    } MI_PERIFERICO__STATUS__RESERVED2__out_t;

    typedef struct {
        MI_PERIFERICO__STATUS__CNT_DROP__out_t CNT_DROP;
        MI_PERIFERICO__STATUS__RX_LVL__out_t RX_LVL;
        MI_PERIFERICO__STATUS__RESERVED1__out_t RESERVED1;
        MI_PERIFERICO__STATUS__TX_LVL__out_t TX_LVL;
        MI_PERIFERICO__STATUS__RESERVED2__out_t RESERVED2;
    } MI_PERIFERICO__STATUS__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQEN__RX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQEN__RX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQEN__TX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQEN__TX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQEN__MAX_DROP__out_t;

    typedef struct {
        logic [26:0] value;
    } MI_PERIFERICO__IRQEN__RESERVED__out_t;

    typedef struct {
        MI_PERIFERICO__IRQEN__RX_FIFO_EMPTY__out_t RX_FIFO_EMPTY;
        MI_PERIFERICO__IRQEN__RX_FIFO_FULL__out_t RX_FIFO_FULL;
        MI_PERIFERICO__IRQEN__TX_FIFO_EMPTY__out_t TX_FIFO_EMPTY;
        MI_PERIFERICO__IRQEN__TX_FIFO_FULL__out_t TX_FIFO_FULL;
        MI_PERIFERICO__IRQEN__MAX_DROP__out_t MAX_DROP;
        MI_PERIFERICO__IRQEN__RESERVED__out_t RESERVED;
    } MI_PERIFERICO__IRQEN__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQ__RX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQ__RX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQ__TX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQ__TX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } MI_PERIFERICO__IRQ__MAX_DROP__out_t;

    typedef struct {
        logic [26:0] value;
    } MI_PERIFERICO__IRQ__RESERVED__out_t;

    typedef struct {
        MI_PERIFERICO__IRQ__RX_FIFO_EMPTY__out_t RX_FIFO_EMPTY;
        MI_PERIFERICO__IRQ__RX_FIFO_FULL__out_t RX_FIFO_FULL;
        MI_PERIFERICO__IRQ__TX_FIFO_EMPTY__out_t TX_FIFO_EMPTY;
        MI_PERIFERICO__IRQ__TX_FIFO_FULL__out_t TX_FIFO_FULL;
        MI_PERIFERICO__IRQ__MAX_DROP__out_t MAX_DROP;
        MI_PERIFERICO__IRQ__RESERVED__out_t RESERVED;
    } MI_PERIFERICO__IRQ__out_t;

    typedef struct {
        MI_PERIFERICO__CTRL__out_t CTRL;
        MI_PERIFERICO__STATUS__out_t STATUS;
        MI_PERIFERICO__IRQEN__out_t IRQEN;
        MI_PERIFERICO__IRQ__out_t IRQ;
    } MI_PERIFERICO__out_t;
endpackage
