// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package APB_REGS_pkg;

    localparam APB_REGS_DATA_WIDTH = 32;
    localparam APB_REGS_MIN_ADDR_WIDTH = 8;
    localparam APB_REGS_SIZE = 'hf8;

    typedef struct {
        logic [2:0] value;
    } APB_REGS__CTRL__SIZE__out_t;

    typedef struct {
        logic [4:0] value;
    } APB_REGS__CTRL__reserved1__out_t;

    typedef struct {
        logic [1:0] value;
    } APB_REGS__CTRL__OFFSET__out_t;

    typedef struct {
        logic [5:0] value;
    } APB_REGS__CTRL__reserved2__out_t;

    typedef struct {
        logic value;
    } APB_REGS__CTRL__CLR__out_t;

    typedef struct {
        logic [14:0] value;
    } APB_REGS__CTRL__reserved3__out_t;

    typedef struct {
        APB_REGS__CTRL__SIZE__out_t SIZE;
        APB_REGS__CTRL__reserved1__out_t reserved1;
        APB_REGS__CTRL__OFFSET__out_t OFFSET;
        APB_REGS__CTRL__reserved2__out_t reserved2;
        APB_REGS__CTRL__CLR__out_t CLR;
        APB_REGS__CTRL__reserved3__out_t reserved3;
    } APB_REGS__CTRL__out_t;

    typedef struct {
        logic [7:0] value;
    } APB_REGS__STATUS__CNT_DROP__out_t;

    typedef struct {
        logic [3:0] value;
    } APB_REGS__STATUS__RX_LVL__out_t;

    typedef struct {
        logic [3:0] value;
    } APB_REGS__STATUS__reserved4__out_t;

    typedef struct {
        logic [3:0] value;
    } APB_REGS__STATUS__TX_LVL__out_t;

    typedef struct {
        logic [11:0] value;
    } APB_REGS__STATUS__reserved5__out_t;

    typedef struct {
        APB_REGS__STATUS__CNT_DROP__out_t CNT_DROP;
        APB_REGS__STATUS__RX_LVL__out_t RX_LVL;
        APB_REGS__STATUS__reserved4__out_t reserved4;
        APB_REGS__STATUS__TX_LVL__out_t TX_LVL;
        APB_REGS__STATUS__reserved5__out_t reserved5;
    } APB_REGS__STATUS__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ_EN__RX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ_EN__RX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ_EN__TX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ_EN__TX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ_EN__MAX_DROP__out_t;

    typedef struct {
        logic [26:0] value;
    } APB_REGS__IRQ_EN__reserved6__out_t;

    typedef struct {
        APB_REGS__IRQ_EN__RX_FIFO_EMPTY__out_t RX_FIFO_EMPTY;
        APB_REGS__IRQ_EN__RX_FIFO_FULL__out_t RX_FIFO_FULL;
        APB_REGS__IRQ_EN__TX_FIFO_EMPTY__out_t TX_FIFO_EMPTY;
        APB_REGS__IRQ_EN__TX_FIFO_FULL__out_t TX_FIFO_FULL;
        APB_REGS__IRQ_EN__MAX_DROP__out_t MAX_DROP;
        APB_REGS__IRQ_EN__reserved6__out_t reserved6;
    } APB_REGS__IRQ_EN__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ__RX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ__RX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ__TX_FIFO_EMPTY__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ__TX_FIFO_FULL__out_t;

    typedef struct {
        logic value;
    } APB_REGS__IRQ__MAX_DROP__out_t;

    typedef struct {
        logic [26:0] value;
    } APB_REGS__IRQ__reserved7__out_t;

    typedef struct {
        APB_REGS__IRQ__RX_FIFO_EMPTY__out_t RX_FIFO_EMPTY;
        APB_REGS__IRQ__RX_FIFO_FULL__out_t RX_FIFO_FULL;
        APB_REGS__IRQ__TX_FIFO_EMPTY__out_t TX_FIFO_EMPTY;
        APB_REGS__IRQ__TX_FIFO_FULL__out_t TX_FIFO_FULL;
        APB_REGS__IRQ__MAX_DROP__out_t MAX_DROP;
        APB_REGS__IRQ__reserved7__out_t reserved7;
    } APB_REGS__IRQ__out_t;

    typedef struct {
        APB_REGS__CTRL__out_t CTRL;
        APB_REGS__STATUS__out_t STATUS;
        APB_REGS__IRQ_EN__out_t IRQ_EN;
        APB_REGS__IRQ__out_t IRQ;
    } APB_REGS__out_t;
endpackage
