// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module APB_REGS (
        input wire clk,
        input wire rst,

        apb3_intf.slave s_apb,

        output APB_REGS_pkg::APB_REGS__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [7:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    `ifndef SYNTHESIS
        initial begin
            assert_bad_addr_width: assert($bits(s_apb.PADDR) >= APB_REGS_pkg::APB_REGS_MIN_ADDR_WIDTH)
                else $error("Interface address width of %0d is too small. Shall be at least %0d bits", $bits(s_apb.PADDR), APB_REGS_pkg::APB_REGS_MIN_ADDR_WIDTH);
            assert_bad_data_width: assert($bits(s_apb.PWDATA) == APB_REGS_pkg::APB_REGS_DATA_WIDTH)
                else $error("Interface data width of %0d is incorrect. Shall be %0d bits", $bits(s_apb.PWDATA), APB_REGS_pkg::APB_REGS_DATA_WIDTH);
        end
    `endif

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb.PSEL) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb.PWRITE;
                    cpuif_addr <= {s_apb.PADDR[7:2], 2'b0};
                    cpuif_wr_data <= s_apb.PWDATA;
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end
    assign cpuif_wr_biten = '1;

    // Response
    assign s_apb.PREADY = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb.PRDATA = cpuif_rd_data;
    assign s_apb.PSLVERR = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic CTRL;
        logic STATUS;
        logic IRQ_EN;
        logic IRQ;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.CTRL = cpuif_req_masked & (cpuif_addr == 8'h0);
        decoded_reg_strb.STATUS = cpuif_req_masked & (cpuif_addr == 8'hc);
        decoded_reg_strb.IRQ_EN = cpuif_req_masked & (cpuif_addr == 8'hf0);
        decoded_reg_strb.IRQ = cpuif_req_masked & (cpuif_addr == 8'hf4);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [2:0] next;
                logic load_next;
            } SIZE;
            struct {
                logic [1:0] next;
                logic load_next;
            } OFFSET;
            struct {
                logic next;
                logic load_next;
            } CLR;
        } CTRL;
        struct {
            struct {
                logic next;
                logic load_next;
            } RX_FIFO_EMPTY;
            struct {
                logic next;
                logic load_next;
            } RX_FIFO_FULL;
            struct {
                logic next;
                logic load_next;
            } TX_FIFO_EMPTY;
            struct {
                logic next;
                logic load_next;
            } TX_FIFO_FULL;
            struct {
                logic next;
                logic load_next;
            } MAX_DROP;
        } IRQ_EN;
        struct {
            struct {
                logic next;
                logic load_next;
            } RX_FIFO_EMPTY;
            struct {
                logic next;
                logic load_next;
            } RX_FIFO_FULL;
            struct {
                logic next;
                logic load_next;
            } TX_FIFO_EMPTY;
            struct {
                logic next;
                logic load_next;
            } TX_FIFO_FULL;
            struct {
                logic next;
                logic load_next;
            } MAX_DROP;
        } IRQ;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [2:0] value;
            } SIZE;
            struct {
                logic [1:0] value;
            } OFFSET;
            struct {
                logic value;
            } CLR;
        } CTRL;
        struct {
            struct {
                logic value;
            } RX_FIFO_EMPTY;
            struct {
                logic value;
            } RX_FIFO_FULL;
            struct {
                logic value;
            } TX_FIFO_EMPTY;
            struct {
                logic value;
            } TX_FIFO_FULL;
            struct {
                logic value;
            } MAX_DROP;
        } IRQ_EN;
        struct {
            struct {
                logic value;
            } RX_FIFO_EMPTY;
            struct {
                logic value;
            } RX_FIFO_FULL;
            struct {
                logic value;
            } TX_FIFO_EMPTY;
            struct {
                logic value;
            } TX_FIFO_FULL;
            struct {
                logic value;
            } MAX_DROP;
        } IRQ;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: APB_REGS.CTRL.SIZE
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.SIZE.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.SIZE.value & ~decoded_wr_biten[2:0]) | (decoded_wr_data[2:0] & decoded_wr_biten[2:0]);
            load_next_c = '1;
        end
        field_combo.CTRL.SIZE.next = next_c;
        field_combo.CTRL.SIZE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.SIZE.value <= 3'h1;
        end else begin
            if(field_combo.CTRL.SIZE.load_next) begin
                field_storage.CTRL.SIZE.value <= field_combo.CTRL.SIZE.next;
            end
        end
    end
    assign hwif_out.CTRL.SIZE.value = field_storage.CTRL.SIZE.value;
    assign hwif_out.CTRL.reserved1.value = 5'h0;
    // Field: APB_REGS.CTRL.OFFSET
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.OFFSET.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.OFFSET.value & ~decoded_wr_biten[9:8]) | (decoded_wr_data[9:8] & decoded_wr_biten[9:8]);
            load_next_c = '1;
        end
        field_combo.CTRL.OFFSET.next = next_c;
        field_combo.CTRL.OFFSET.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.OFFSET.value <= 2'h0;
        end else begin
            if(field_combo.CTRL.OFFSET.load_next) begin
                field_storage.CTRL.OFFSET.value <= field_combo.CTRL.OFFSET.next;
            end
        end
    end
    assign hwif_out.CTRL.OFFSET.value = field_storage.CTRL.OFFSET.value;
    assign hwif_out.CTRL.reserved2.value = 6'h0;
    // Field: APB_REGS.CTRL.CLR
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.CLR.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.CLR.value & ~decoded_wr_biten[16:16]) | (decoded_wr_data[16:16] & decoded_wr_biten[16:16]);
            load_next_c = '1;
        end
        field_combo.CTRL.CLR.next = next_c;
        field_combo.CTRL.CLR.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.CLR.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.CLR.load_next) begin
                field_storage.CTRL.CLR.value <= field_combo.CTRL.CLR.next;
            end
        end
    end
    assign hwif_out.CTRL.CLR.value = field_storage.CTRL.CLR.value;
    assign hwif_out.CTRL.reserved3.value = 15'h0;
    assign hwif_out.STATUS.CNT_DROP.value = 8'h0;
    assign hwif_out.STATUS.RX_LVL.value = 4'h0;
    assign hwif_out.STATUS.reserved4.value = 4'h0;
    assign hwif_out.STATUS.TX_LVL.value = 4'h0;
    assign hwif_out.STATUS.reserved5.value = 12'h0;
    // Field: APB_REGS.IRQ_EN.RX_FIFO_EMPTY
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_EN.RX_FIFO_EMPTY.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IRQ_EN.RX_FIFO_EMPTY.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.IRQ_EN.RX_FIFO_EMPTY.next = next_c;
        field_combo.IRQ_EN.RX_FIFO_EMPTY.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_EN.RX_FIFO_EMPTY.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_EN.RX_FIFO_EMPTY.load_next) begin
                field_storage.IRQ_EN.RX_FIFO_EMPTY.value <= field_combo.IRQ_EN.RX_FIFO_EMPTY.next;
            end
        end
    end
    assign hwif_out.IRQ_EN.RX_FIFO_EMPTY.value = field_storage.IRQ_EN.RX_FIFO_EMPTY.value;
    // Field: APB_REGS.IRQ_EN.RX_FIFO_FULL
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_EN.RX_FIFO_FULL.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IRQ_EN.RX_FIFO_FULL.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.IRQ_EN.RX_FIFO_FULL.next = next_c;
        field_combo.IRQ_EN.RX_FIFO_FULL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_EN.RX_FIFO_FULL.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_EN.RX_FIFO_FULL.load_next) begin
                field_storage.IRQ_EN.RX_FIFO_FULL.value <= field_combo.IRQ_EN.RX_FIFO_FULL.next;
            end
        end
    end
    assign hwif_out.IRQ_EN.RX_FIFO_FULL.value = field_storage.IRQ_EN.RX_FIFO_FULL.value;
    // Field: APB_REGS.IRQ_EN.TX_FIFO_EMPTY
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_EN.TX_FIFO_EMPTY.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IRQ_EN.TX_FIFO_EMPTY.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.IRQ_EN.TX_FIFO_EMPTY.next = next_c;
        field_combo.IRQ_EN.TX_FIFO_EMPTY.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_EN.TX_FIFO_EMPTY.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_EN.TX_FIFO_EMPTY.load_next) begin
                field_storage.IRQ_EN.TX_FIFO_EMPTY.value <= field_combo.IRQ_EN.TX_FIFO_EMPTY.next;
            end
        end
    end
    assign hwif_out.IRQ_EN.TX_FIFO_EMPTY.value = field_storage.IRQ_EN.TX_FIFO_EMPTY.value;
    // Field: APB_REGS.IRQ_EN.TX_FIFO_FULL
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_EN.TX_FIFO_FULL.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IRQ_EN.TX_FIFO_FULL.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.IRQ_EN.TX_FIFO_FULL.next = next_c;
        field_combo.IRQ_EN.TX_FIFO_FULL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_EN.TX_FIFO_FULL.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_EN.TX_FIFO_FULL.load_next) begin
                field_storage.IRQ_EN.TX_FIFO_FULL.value <= field_combo.IRQ_EN.TX_FIFO_FULL.next;
            end
        end
    end
    assign hwif_out.IRQ_EN.TX_FIFO_FULL.value = field_storage.IRQ_EN.TX_FIFO_FULL.value;
    // Field: APB_REGS.IRQ_EN.MAX_DROP
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ_EN.MAX_DROP.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ_EN && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IRQ_EN.MAX_DROP.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.IRQ_EN.MAX_DROP.next = next_c;
        field_combo.IRQ_EN.MAX_DROP.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ_EN.MAX_DROP.value <= 1'h0;
        end else begin
            if(field_combo.IRQ_EN.MAX_DROP.load_next) begin
                field_storage.IRQ_EN.MAX_DROP.value <= field_combo.IRQ_EN.MAX_DROP.next;
            end
        end
    end
    assign hwif_out.IRQ_EN.MAX_DROP.value = field_storage.IRQ_EN.MAX_DROP.value;
    assign hwif_out.IRQ_EN.reserved6.value = 27'h0;
    // Field: APB_REGS.IRQ.RX_FIFO_EMPTY
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ.RX_FIFO_EMPTY.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.IRQ.RX_FIFO_EMPTY.value & ~(decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.IRQ.RX_FIFO_EMPTY.next = next_c;
        field_combo.IRQ.RX_FIFO_EMPTY.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ.RX_FIFO_EMPTY.value <= 1'h0;
        end else begin
            if(field_combo.IRQ.RX_FIFO_EMPTY.load_next) begin
                field_storage.IRQ.RX_FIFO_EMPTY.value <= field_combo.IRQ.RX_FIFO_EMPTY.next;
            end
        end
    end
    assign hwif_out.IRQ.RX_FIFO_EMPTY.value = field_storage.IRQ.RX_FIFO_EMPTY.value;
    // Field: APB_REGS.IRQ.RX_FIFO_FULL
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ.RX_FIFO_FULL.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.IRQ.RX_FIFO_FULL.value & ~(decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.IRQ.RX_FIFO_FULL.next = next_c;
        field_combo.IRQ.RX_FIFO_FULL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ.RX_FIFO_FULL.value <= 1'h0;
        end else begin
            if(field_combo.IRQ.RX_FIFO_FULL.load_next) begin
                field_storage.IRQ.RX_FIFO_FULL.value <= field_combo.IRQ.RX_FIFO_FULL.next;
            end
        end
    end
    assign hwif_out.IRQ.RX_FIFO_FULL.value = field_storage.IRQ.RX_FIFO_FULL.value;
    // Field: APB_REGS.IRQ.TX_FIFO_EMPTY
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ.TX_FIFO_EMPTY.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.IRQ.TX_FIFO_EMPTY.value & ~(decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.IRQ.TX_FIFO_EMPTY.next = next_c;
        field_combo.IRQ.TX_FIFO_EMPTY.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ.TX_FIFO_EMPTY.value <= 1'h0;
        end else begin
            if(field_combo.IRQ.TX_FIFO_EMPTY.load_next) begin
                field_storage.IRQ.TX_FIFO_EMPTY.value <= field_combo.IRQ.TX_FIFO_EMPTY.next;
            end
        end
    end
    assign hwif_out.IRQ.TX_FIFO_EMPTY.value = field_storage.IRQ.TX_FIFO_EMPTY.value;
    // Field: APB_REGS.IRQ.TX_FIFO_FULL
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ.TX_FIFO_FULL.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.IRQ.TX_FIFO_FULL.value & ~(decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.IRQ.TX_FIFO_FULL.next = next_c;
        field_combo.IRQ.TX_FIFO_FULL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ.TX_FIFO_FULL.value <= 1'h0;
        end else begin
            if(field_combo.IRQ.TX_FIFO_FULL.load_next) begin
                field_storage.IRQ.TX_FIFO_FULL.value <= field_combo.IRQ.TX_FIFO_FULL.next;
            end
        end
    end
    assign hwif_out.IRQ.TX_FIFO_FULL.value = field_storage.IRQ.TX_FIFO_FULL.value;
    // Field: APB_REGS.IRQ.MAX_DROP
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IRQ.MAX_DROP.value;
        load_next_c = '0;
        if(decoded_reg_strb.IRQ && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.IRQ.MAX_DROP.value & ~(decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.IRQ.MAX_DROP.next = next_c;
        field_combo.IRQ.MAX_DROP.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IRQ.MAX_DROP.value <= 1'h0;
        end else begin
            if(field_combo.IRQ.MAX_DROP.load_next) begin
                field_storage.IRQ.MAX_DROP.value <= field_combo.IRQ.MAX_DROP.next;
            end
        end
    end
    assign hwif_out.IRQ.MAX_DROP.value = field_storage.IRQ.MAX_DROP.value;
    assign hwif_out.IRQ.reserved7.value = 27'h0;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[4];
    assign readback_array[0][2:0] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.SIZE.value : '0;
    assign readback_array[0][7:3] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? 5'h0 : '0;
    assign readback_array[0][9:8] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.OFFSET.value : '0;
    assign readback_array[0][15:10] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? 6'h0 : '0;
    assign readback_array[0][16:16] = '0;
    assign readback_array[0][31:17] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? 15'h0 : '0;
    assign readback_array[1][7:0] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? 8'h0 : '0;
    assign readback_array[1][11:8] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? 4'h0 : '0;
    assign readback_array[1][15:12] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? 4'h0 : '0;
    assign readback_array[1][19:16] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? 4'h0 : '0;
    assign readback_array[1][31:20] = (decoded_reg_strb.STATUS && !decoded_req_is_wr) ? 12'h0 : '0;
    assign readback_array[2][0:0] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? field_storage.IRQ_EN.RX_FIFO_EMPTY.value : '0;
    assign readback_array[2][1:1] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? field_storage.IRQ_EN.RX_FIFO_FULL.value : '0;
    assign readback_array[2][2:2] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? field_storage.IRQ_EN.TX_FIFO_EMPTY.value : '0;
    assign readback_array[2][3:3] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? field_storage.IRQ_EN.TX_FIFO_FULL.value : '0;
    assign readback_array[2][4:4] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? field_storage.IRQ_EN.MAX_DROP.value : '0;
    assign readback_array[2][31:5] = (decoded_reg_strb.IRQ_EN && !decoded_req_is_wr) ? 27'h0 : '0;
    assign readback_array[3][4:0] = '0;
    assign readback_array[3][31:5] = (decoded_reg_strb.IRQ && !decoded_req_is_wr) ? 27'h0 : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<4; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
